Aharoni-Lab/mio

- miniscope_io/io.py
- tests/test_io.py
Previously, sdcard would try and `resolve` every path given to it. Now that behavior has been removed, allowing both relative and absolute paths.
reinstated throwing an exception when config can't be read, as that should stop any further use of the object since something has gone wrong with reading from it
Related to: 
- https://github.com/Aharoni-Lab/miniscope-io/pull/8#issuecomment-1704502701
Closes:
- https://github.com/Aharoni-Lab/miniscope-io/issues/6
@t-sasatani I removed the try block around reading the config which was also added in https://github.com/Aharoni-Lab/miniscope-io/commit/bc9370a612ae69b9d182f08f8379762026004ba6 - i figured removing the `resolve` addresses the reason it was added? seems like throwing an I/O error there if the config can't be read is good to do, since …
> bugfix: relative and absolute paths

- poetry.lock
- pyproject.toml
This is a quick update to avoid issues on Windows. `matplotlib 3.9.1` has issues on Windows, so I just specified the version to `>3.9.1` to use `3.9.2`, which was released a few days ago.
- https://github.com/matplotlib/matplotlib/issues/28551
> Update matplotlib version for Windows compatibility

- docs/device/test_device.md
- miniscope_io/data/config/WLMS_v02_200px.yml
- miniscope_io/models/stream.py
- miniscope_io/stream_daq.py
- tests/test_stream_daq.py
This patch PR handles dummy words at the beginning of the data buffers. This gives the FPGA a little bit of time to recover clock signals before the actual preamble detection starts. It runs the same as `v0.4.0` if `dummy_bytes = 0`. 
@MarcelMB found that signal polarity between buffer transfers affects the decoder's performance. We noticed that clock recovery might not be working well for the first few bits, and this PR addresses that. Now, the wired image transfer works with almost no errors, and I think the wireless runs more stable than before (I'm not sure about this, but it might also solve #36.)
> Support dummy words in stream buffer beginning

- docs/meta/changelog.md
- miniscope_io/data/config/WLMS_v02_200px.yml
- miniscope_io/formats/stream.py
- miniscope_io/models/stream.py
- miniscope_io/stream_daq.py
- pyproject.toml
- tests/conftest.py
- tests/data/config/stream_daq_test_200px.yml
- tests/test_models/test_model_stream.py
I'm doing this quick PR because I needed it for hardware experiments. This PR is just for converting ADC to voltage in the `StreamBufferHeader` model using the YAML device config. I think I'll update to `v0.4.1` combined with #41 if this looks quick enough.
> ADC-voltage conversion in StreamBufferHeader model

- .github/workflows/docs-preview.yml
I'm gonna :self-high-five: this one, all it is doing is adding a CI action that adds a link to the readthedocs build for a PR to the OP issue when a PR is opened:
see:
https://github.com/readthedocs/actions/tree/v1/preview
> [ci] Add readthedocs preview links to PRs

- miniscope_io/__init__.py
- pyproject.toml
instead of handcoding the version, let's just use the git tags. this is en route to continuous deployment where we just cut a new version by pushing a new tag. it will also let us give unambiguous version information for provenance sake when we start embedding version in configs and output data
- `v0.0.0`:  when you are on a clean checkout (nothing changed, nothing staged) of a commit with a tag with the pattern `v.*`, that is the version. i.e. when a CI/CD action is triggered by a new tag starting with v, that will be the version. We don't use tags for anything else atm so there shouldn't be a problem of accidentally making a non-version tag that starts with `v`, but in any case we'll deal with that in the cd action.
- `v0.0.0.dev{n}+{hash}` (e.g. `0.4.2.dev8+g56b32b7`) where `n` is the …
> use dynamic versioning

- docs/api/stream_daq.md
- docs/cli/config.md
- docs/cli/index.md
- docs/cli/stream.md
- docs/cli/update.md
- docs/conf.py
- docs/guide/config.md
- docs/index.md
- miniscope_io/cli/config.py
- miniscope_io/cli/main.py
- miniscope_io/logging.py
- miniscope_io/models/config.py
- miniscope_io/models/mixins.py
- pdm.lock
- pyproject.toml
- tests/fixtures.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_logging.py
This PR ports some stuff i have worked on in linkml over to miniscope-io.
Specifically we
- Adds a configurable `user_dir` source of config - currently there is a place to set `base_dir` but no way to get config from that directory, but now one can define global config there too.
- Adds other sources of config because why the hell not - currently one can use ` .env` file, but this adds the ability to use (in order of priority, high to low)...
- `mio_config.yaml` in current directory
- `pyproject.toml` - the `[tool.miniscope_io.config]` table
- `mio_config.yaml` in a custom user directory
- `mio_config.yaml` in a fixed global directory 
- Adds cli commands to
- create/set a user directory
- show user/global configs
- show locations of user and global config files
This also improves testing …
> Global and User config, CLI config

- .github/workflows/docs-preview.yml
- docs/cli/config.md
- docs/cli/device.md
- docs/cli/index.md
- docs/cli/stream.md
- docs/cli/update.md
- docs/meta/changelog.md
Just a minor PR to update the changelog before I push v0.6 and push our first release as `mio` :)
----
📚 Documentation preview 📚: https://mio--87.org.readthedocs.build/en/87/
> [chore] Bump to v0.6, changelog

- mio/cli/stream.py
Added description to device config id in stream.py about id for CLI            "This is currently the id located in the first line of the YAML config file "
----
📚 Documentation preview 📚: https://miniscope-io--88.org.readthedocs.build/en/88/
> Added info about what id is for device config about YAML for CLI

- .github/workflows/docs-test.yml
- .github/workflows/tests.yml
Since we're doing stacked up PRs, we should be running tests against each of them to avoid errors piling up
----
📚 Documentation preview 📚: https://miniscope-io--95.org.readthedocs.build/en/95/
> [ci] Run tests against any PR

- docs/api/preprocessing_guide.md
- docs/api/process/frame_helper.md
- docs/api/process/index.md
- docs/api/process/video.md
- docs/api/process/zstack_helper.md
- docs/index.md
- mio/data/config/process/denoise_example.yml
- mio/data/config/process/denoise_example_mean_error.yml
- mio/models/process.py
- mio/process/frame_helper.py
- mio/process/video.py
- mio/process/zstack_helper.py
- tests/test_process/test_frame_helper.py
- tests/test_process_video.py
The `_detect_black_pixels` looks if consecutive pixels in a row are black
` black_pixel_consecutive_threshold: 5 # If 5 consecutive pixels in a row are black, discard the frame
black_pixel_value_threshold: 16 # Any pixel value ≤ 16 is considered "black"`
those two parameters in denoise_examle.yaml decides how many consecutive pixels need to be black and what is defined as black (black pixels don't have a value of zero but when I checked was like 16)
updated `detect_frame_with_noisy_buffer` to work with two methods simultaneously
added `test_frame_helper.py` to the test to also test the gradient method on blacked_out subcategory frames (since the gradient method now also incorporates finding black frames)
test all pass (except the xfail that jonny marked for obvious reasons)
curious about …
> Combined detector / black area detector / bugfix process frame index

- mio/models/mixins.py
- mio/types.py
- tests/test_mixins.py
@MarcelMB let me know that one couldn't pass an absolute (or any) path in the `-c` flag in the cli with this traceback (truncated)
```
File “miniscope-io/mio/stream_daq.py”, line 103, in __init__
self.config = StreamDevConfig.from_any(device_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “miniscope-io/mio/models/mixins.py”, line 158, in from_any
elif valid_config_id(source):
^^^^^^^^^^^^^^^^^^^^^^^
File “miniscope-io/mio/types.py”, line 66, in valid_config_id
return bool(re.fullmatch(CONFIG_ID_PATTERN, val))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “python3.11/re/__init__.py”, line 171, in fullmatch
return _compile(pattern, flags).fullmatch(string)          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got ‘PosixPath’
```
Very simple, …
> Actually handle paths in `ConfigYAMLMixin.from_any`

- .github/workflows/tests.yml
- mio/io.py
- mio/models/frames.py
- mio/stream_daq.py
- pdm.lock
- pyproject.toml
- tests/test_models/test_model_frames.py
- tests/test_stream_daq.py
This PR primarily integrates the bugfixes discussed in:
- #111 
1. **FFmpeg-based `VideoWriter` class**: Open-cv-based video writers cause problems, so this PR switches to FFMpeg-based stuff. I haven't changed the real-time video displays and `.png` export because I assume it's very unlikely these are accidentally compressed, like the video export.
2. **Byte/bit operation moved to preprocessing**: This is still probably not in the ideal place, but I moved it to the earliest point I could without coordinating with the firmware part.
3. Removed USART support (for now).
This PR comes from the `feat-preprocess` branch because the `VideoWriter` class was isolated there to use it in the preprocessing feature.
----
📚 Documentation preview 📚: …
> ffmpeg-based `VideoWriter`

- .github/workflows/tests.yml
- mio/models/mixins.py
- tests/conftest.py
- tests/fixtures.py
- tests/test_mixins.py
python 3.13 removed the ability to use `@classmethod`s and `@property` together - https://docs.python.org/3.13/library/functions.html#classmethod
This causes a bug when using `id`s to load configs like:
```
>       globs = [src.rglob("*.y*ml") for src in cls.config_sources]
E       TypeError: 'method' object is not iterable
```
so this is just a PR to switch it to being a classmethod. 
first committing updated ci action that tests against 3.13 to confirm failure, then committing fix.
- confirmed correctly failing in python 3.13 only - https://github.com/Aharoni-Lab/mio/actions/runs/13478817474?pr=109
- confirmed after fix no longer failing - https://github.com/Aharoni-Lab/mio/actions/runs/13478866148?pr=109
While refactoring the method, i noticed that usages were not being detected …
> Make `config_sources` a classmethod rather than a class property

- mio/devices/mocks.py
- mio/devices/opalkelly.py
- mio/stream_daq.py
- mio/types.py
- pyproject.toml
- tests/test_devices/test_okdev.py
- tests/test_stream_daq.py
Doing a live programming demo with @hsemwal , and for ~secret miniscope type~ we want to be able to test the pixel-wise and frame-wise processing of the data outside of the streamdaq class as we get it on its feet. since it's pretty hard to do that as is, this is a function-neutral change to just split out the iteration (as it would be done in the guts of the streamdaq) into a separate function.
i'm not sure how much we've actually said this on this repo, but all the pipelining stuff is getting split off into a separate package because it felt sort of absurd to do it all in `mio`, so until that's done, will be making smaller more targeted refactors.
should be *relatively* self explanatory, the one thing that might not be is making the stream device into an iterator with `__next__` and …
> Separate buffer-splitting in `_fpga_recv` into a generator function

- mio/utils.py
- tests/fixtures.py
- tests/test_gs/test_daq.py
add a test to use the bright/dark sample to assert that the frame processing is *basically correct* - we have a sample where the first frames are bright, and the later frames are dark(ish). so we just assert that basic fact about the data. 
it's *not* a very strict test for correctness, but it's a basic sanity check that we are getting bit/byte ordering "sort of right" 
----
📚 Documentation preview 📚: https://miniscope-io--129.org.readthedocs.build/en/129/
> msus - test frame processing values with bright/dark sample

- .github/workflows/tests.yml
- README.md
- docs/meta/changelog.md
- mio/io.py
- mio/stream_daq.py
- tests/test_io.py
- tests/test_stream_daq.py
@hsemwal reported an issue where the header metadata looked correct when it was being printed to stdout, but the csv being written was incorrect s.t. each buffer was being written multiple times....
<details>
<summary>expand/collapse example</summary>
|linked_list|frame_num                    |buffer_count|frame_buffer_count                           |write_buffer_count|dropped_buffer_count|timestamp|pixel_count|write_timestamp|battery_voltage_raw|input_voltage_raw|unix_time         |
|-----------|-----------------------------|------------|---------------------------------------------|------------------|--------------------|---------|-----------|---------------|-------------------|-----------------|------------------|
|11         |12821                        |102571      |3 …
> Fix csvwriter header alignment, fix writing duplicated header rows

- .github/workflows/tests.yml
- pdm.lock
- pyproject.toml
- tests/conftest.py
The way to manage subprocesses in `pytest-cov` has changed, causing test failure. 
This PR removes the outdated
```
from pytest_cov.embed import cleanup_on_sigterm
cleanup_on_sigterm()
```
and replaces it with the updated recommendation
```toml
[tool.coverage.run]
patch = ["subprocess"]
```
https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html
----
📚 Documentation preview 📚: https://miniscope-io--134.org.readthedocs.build/en/134/
> Update subprocess handling of CI/CD (`pytest-cov`)

- docs/meta/changelog.md
- mio/cli/common.py
- mio/cli/stream.py
- mio/data/config/process/bpf_example.yml
- mio/data/config/process/denoise_example.yml
- mio/data/config/process/denoise_example_mean_error.yml
- mio/data/config/process/remove_stripe_example.yml
- mio/models/process.py
- mio/process/frame_helper.py
- mio/stream_daq.py
- tests/data/config/remove_stripe_example.yml
- tests/test_cli.py
- tests/test_stream_daq.py
Online (real-time) bandpass filtering integrated with the `stream` command.
```
mio stream capture -c wireless-200px -f remove_stripe_example
```
This only filters the video preview, leaving the file output as is.
----
📚 Documentation preview 📚: https://miniscope-io--121.org.readthedocs.build/en/121/
> Online frequency filter (stripe removal)

- docs/cli/hash.md
- docs/cli/index.md
- docs/meta/changelog.md
- mio/cli/main.py
- mio/cli/util.py
Tiny PR for exposing hash_video command to CLI
```bash
mio hash VIDEO_PATH
```
----
📚 Documentation preview 📚: https://miniscope-io--103.org.readthedocs.build/en/103/
> Expose hash video function to mio cli
